### ISSUE TITLE
Is there anyway to unload loaded content?

### ISSUE THREAD

**Issue by iRYO400** [vic797/prowebview#2]
Tried two ways accepted ways:
1) `webView.loadUrl("about:blank");` - app crashes immediately without any "App crashed" dialogs and stacktrace is super big https://pastebin.com/j9rHxkun

2) `view.loadUrl("javascript:document.open();document.close();");` in the monitor it says me 
`W/chromium: [WARNING:navigator_impl.cc(327)] Refusing to load for invalid virtual URL: http://javascript:document.open();document.close();/`

and deleteData() doesn't help, all data stay untouched

and yes, you made awesome stuff, it's really easy to use, love it

**Comment by vic797** [comment]
1. `ProWebView.loadUrl("about:blank");` creates an infinite loop. The method `loadUrl("about:blank")` calls `showBlank()` witch calls again `loadUrl("about:blank")` instead of `super.loadUrl("about:blank")`.
2. ProWebView adds automatically the protocol if missing. I didn't consider the `javascript:` protocol.

I will fix that.
